
- name: Prepare the node
  shell: >
        mkdir -p {{ okd_root }}

        chmod -R 777 {{ okd_root }}

- name: Install the CLI
  shell: >
        curl -L -0 {{openshift_cli_url}} | tar -zx -C /tmp

        cd /tmp/op* && sudo mv oc /usr/local && sudo ln -sf /usr/local/oc
        /usr/local/bin/oc
  
- name: Create the OpenShift cluster-create script
  shell: >
        echo "/usr/local/oc cluster up --public-hostname='{{ hostname }}.{{ public_dns_zone }}'
        --base-dir={{ okd_root }}
        --routing-suffix='{{ apps_prefix }}.{{ hostname }}.{{ public_dns_zone }}'
        --enable=persistent-volumes,registry,router,web-console,service-catalog,template-service-broker,centos-imagestreams
        --write-config=true" >>
        {{ okd_root }}/cluster_create

        chmod +x {{ okd_root }}/cluster_create

- name: Create the OpenShift cluster-up script
  shell: >
        echo "/usr/local/oc cluster up --public-hostname='{{ hostname }}.{{ public_dns_zone }}'
        --base-dir={{ okd_root }}" >>
        {{ okd_root }}/cluster_up

        chmod +x {{ okd_root }}/cluster_up

- name: Fix https://github.com/minishift/minishift-centos-iso/issues/222
  shell: echo '172.30.1.1 docker-registry.default.svc' >> /etc/hosts

- name: Install dd-agent
  shell: >
        docker create --name dd-agent --restart always -v /var/run/docker.sock:/var/run/docker.sock:ro -v /proc/:/host/proc/:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -e DD_API_KEY={{ DD_API_KEY }} datadog/agent:latest

        docker start dd-agent
        
#- name: Create default users
#  shell: >
#        htpasswd -c -b {{ okd_root }}/users.htpasswd admin {{ default_passwd }}
#
#        htpasswd -c -b {{ okd_root }}/users.htpasswd developer {{ default_passwd }}

- name: Initialize the OpenShift cluster
  shell: "{{ okd_root }}/cluster_create"

- name: Start the OpenShift cluster
  shell: "{{ okd_root }}/cluster_up"