
- name: Prepare the node
  shell: >
        mkdir -p {{ okd_root }}

        chmod -R 777 {{ okd_root }}

- name: Install the OpenShift CLI
  shell: >
        curl -L -0 {{openshift_cli_url}} | tar -zx -C /tmp

        cd /tmp/op* && sudo mv oc /usr/local && sudo ln -sf /usr/local/oc
        /usr/local/bin/oc
  
- name: Create the cluster init script
  shell: >
        echo "#!/usr/bin/env bash
        
        /usr/local/oc cluster up --public-hostname='{{ hostname }}.{{ public_dns_zone }}'
        --base-dir={{ okd_root }}
        --routing-suffix='{{ apps_prefix }}.{{ hostname }}.{{ public_dns_zone }}'
        --enable=persistent-volumes,registry,router,web-console,service-catalog,template-service-broker,centos-imagestreams
        --write-config=true" >>
        {{ okd_root }}/cluster_init

        chmod +x {{ okd_root }}/cluster_init

- name: Create the cluster start script
  shell: >
        echo "#!/usr/bin/env bash
        
        /usr/local/oc cluster up --public-hostname='{{ hostname }}.{{ public_dns_zone }}' --base-dir={{ okd_root }}" >>
        {{ okd_root }}/cluster_start

        chmod +x {{ okd_root }}/cluster_start

- name: Fix https://github.com/minishift/minishift-centos-iso/issues/222
  shell: echo '172.30.1.1 docker-registry.default.svc' >> /etc/hosts

- name: Install dd-agent
  shell: >
        docker create --name dd-agent --restart always -v /var/run/docker.sock:/var/run/docker.sock:ro -v /proc/:/host/proc/:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -e DD_API_KEY={{ DD_API_KEY }} datadog/agent:latest

        docker start dd-agent
        
- name: Initialize the cluster
  shell: "{{ okd_root }}/cluster_init"

- name: Create a service unit for the cluster
  template:
    src: "../files/okd.service"
    dest: "/etc/systemd/system/okd.service"
  become: true

- name: Enable the service
  shell: "systemctl enable okd"

- name: Start the service
  shell: "systemctl start okd"