
- name: Upgrade packages
  yum: name=* state=latest
  #delegate_to: "{{ base_public_ip }}"
  remote_user: "{{ instance_user }}"
  become: true

- name: Install EPEL
  yum:
    name:
      - "epel-release"
    state: "present"
  #delegate_to: "{{ base_public_ip }}"
  remote_user: "{{ instance_user }}"
  become: true