
- name: Upgrade packages
  yum: name=* state=latest

- name: Install EPEL
  yum:
    name:
      - "epel-release"
    state: "present"

- name: Install essential packages
  yum:
    name:
      - "wget"
      - "net-tools"
      - "ntp"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "kexec-tools"
      - "sos"
      - "psacct"
      - "NetworkManager"
      - "firewalld"
      - "httpd-tools"
    state: "present"

- name: Enable NetworkManager
  shell: "systemctl enable NetworkManager && systemctl restart NetworkManager"

- name: Add a swap file
  shell: >
        dd if=/dev/zero of=/swapfile count=8192 bs=1M

        chmod 600 /swapfile

        mkswap /swapfile

        swapon /swapfile

        echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
