
- name: Update the server instance
  hosts: okd_hosts
  remote_user: "{{ instance_user }}"
  
  roles:
    - role: ../roles/update_centos
    - role: ../roles/install_docker
    - role: ../roles/activate_firewall
    - role: ../roles/reboot